// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Order struct {
	ID         string  `json:"id"`
	Item       string  `json:"item"`
	Amount     int32   `json:"amount"`
	PatientID  int32   `json:"patientId"`
	Medication *string `json:"medication,omitempty"`
	Dosage     *string `json:"dosage,omitempty"`
	Status     string  `json:"status"`
	CreatedAt  *string `json:"createdAt,omitempty"`
	UpdatedAt  *string `json:"updatedAt,omitempty"`
}

type Query struct {
}
