
services:
  api:
    build: .
    container_name: orders-api
    ports:
      - "8080:8080"   # REST
      - "50051:50051" # gRPC
      - "8081:8081"   # GraphQL
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orders
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: orders-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - orders-data:/var/lib/postgresql/data

volumes:
  orders-data:
