version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB=${MONGODB_DB}
      - AUCTION_INTERVAL=${AUCTION_INTERVAL}
    command: sh -c "/auction"
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge